apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  namespace: labgke
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web
        image: southamerica-east1-docker.pkg.dev/aesthetic-guild-338022/myfirstapp/myfirstapp:2.0
        #image: brancomrt/myfirstapp:2.0 
        env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MESSAGE
          value: "LabGKE - Alex Martins" 
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
